/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author abhin
 */
public class destinationbus1 extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public destinationbus1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jgoldbustb = new javax.swing.JButton();
        jbusgoldtt = new javax.swing.JButton();
        jbusgoldtc = new javax.swing.JButton();
        jgoldbus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 420));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHOOSE DESTINATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 60, 470, 48);

        jgoldbustb.setBackground(new java.awt.Color(153, 153, 153));
        jgoldbustb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jgoldbustb.setText("TRIVANDRUM-BENGALURU");
        jgoldbustb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jgoldbustbActionPerformed(evt);
            }
        });
        getContentPane().add(jgoldbustb);
        jgoldbustb.setBounds(50, 150, 500, 50);

        jbusgoldtt.setBackground(new java.awt.Color(153, 153, 153));
        jbusgoldtt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbusgoldtt.setText("TRIVANDRUM-TIRUPATI");
        jbusgoldtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbusgoldttActionPerformed(evt);
            }
        });
        getContentPane().add(jbusgoldtt);
        jbusgoldtt.setBounds(50, 230, 500, 50);

        jbusgoldtc.setBackground(new java.awt.Color(153, 153, 153));
        jbusgoldtc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbusgoldtc.setText("TRIVANDRUM-CHENNAI");
        jbusgoldtc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbusgoldtcActionPerformed(evt);
            }
        });
        getContentPane().add(jbusgoldtc);
        jbusgoldtc.setBounds(50, 320, 500, 50);

        jgoldbus.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhin\\Downloads\\imresizer-1717084224212.jpg")); // NOI18N
        jgoldbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jgoldbusActionPerformed(evt);
            }
        });
        getContentPane().add(jgoldbus);
        jgoldbus.setBounds(490, 20, 50, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhin\\Downloads\\imresizer-1716963249913.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 600, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jgoldbustbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jgoldbustbActionPerformed
        // TODO add your handling code here:
       new busgoldTtoB().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jgoldbustbActionPerformed

    private void jbusgoldttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbusgoldttActionPerformed
        // TODO add your handling code here:
        new BusegoldTtot().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jbusgoldttActionPerformed

    private void jbusgoldtcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbusgoldtcActionPerformed
        // TODO add your handling code here:
        new busgoldTtoC().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbusgoldtcActionPerformed

    private void jgoldbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jgoldbusActionPerformed
        // TODO add your handling code here:
        new packagesbus().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jgoldbusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(destinationbus1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(destinationbus1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(destinationbus1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(destinationbus1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new destinationbus1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbusgoldtc;
    private javax.swing.JButton jbusgoldtt;
    private javax.swing.JButton jgoldbus;
    private javax.swing.JButton jgoldbustb;
    // End of variables declaration//GEN-END:variables
}
