/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author abhin
 */
public class destinationbus2 extends javax.swing.JFrame {

    /**
     * Creates new form destinationbus2
     */
    public destinationbus2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbussilvertb = new javax.swing.JButton();
        jsilverbustt = new javax.swing.JButton();
        jsilverbustc = new javax.swing.JButton();
        jbussilver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 420));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHOOSE DESTINATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 70, 440, 48);

        jbussilvertb.setBackground(new java.awt.Color(153, 153, 153));
        jbussilvertb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbussilvertb.setText("TRIVANDRUM-BENGALURU");
        jbussilvertb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbussilvertbActionPerformed(evt);
            }
        });
        getContentPane().add(jbussilvertb);
        jbussilvertb.setBounds(60, 170, 470, 60);

        jsilverbustt.setBackground(new java.awt.Color(153, 153, 153));
        jsilverbustt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jsilverbustt.setText("TRIVANDRUM-TIRUPATI");
        jsilverbustt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsilverbusttActionPerformed(evt);
            }
        });
        getContentPane().add(jsilverbustt);
        jsilverbustt.setBounds(60, 250, 470, 60);

        jsilverbustc.setBackground(new java.awt.Color(153, 153, 153));
        jsilverbustc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jsilverbustc.setText("TRIVANDRUM-CHENNAI");
        jsilverbustc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsilverbustcActionPerformed(evt);
            }
        });
        getContentPane().add(jsilverbustc);
        jsilverbustc.setBounds(60, 330, 470, 50);

        jbussilver.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhin\\Downloads\\imresizer-1717084224212.jpg")); // NOI18N
        jbussilver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbussilverActionPerformed(evt);
            }
        });
        getContentPane().add(jbussilver);
        jbussilver.setBounds(530, 20, 40, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhin\\Downloads\\imresizer-1716963249913.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 600, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbussilvertbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbussilvertbActionPerformed
        // TODO add your handling code here:
        new BussilverTtoB().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jbussilvertbActionPerformed

    private void jsilverbusttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsilverbusttActionPerformed
        // TODO add your handling code here:
        new bussilverTtot().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jsilverbusttActionPerformed

    private void jsilverbustcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsilverbustcActionPerformed
        // TODO add your handling code here:
        new bussilverTtoC().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jsilverbustcActionPerformed

    private void jbussilverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbussilverActionPerformed
        // TODO add your handling code here:
        new packagesbus().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbussilverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(destinationbus2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(destinationbus2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(destinationbus2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(destinationbus2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new destinationbus2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbussilver;
    private javax.swing.JButton jbussilvertb;
    private javax.swing.JButton jsilverbustc;
    private javax.swing.JButton jsilverbustt;
    // End of variables declaration//GEN-END:variables
}
