/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author abhin
 */
public class destinationtraveller2 extends javax.swing.JFrame {

    /**
     * Creates new form destinationtraveller2
     */
    public destinationtraveller2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jsilvertravellertb = new javax.swing.JButton();
        jsilvertravellertt = new javax.swing.JButton();
        jsilvertravellertc = new javax.swing.JButton();
        jtravellersilver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 420));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHOOSE DESTINATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 70, 288, 32);

        jsilvertravellertb.setBackground(new java.awt.Color(153, 153, 153));
        jsilvertravellertb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jsilvertravellertb.setText("TRIVANDRUM-BENGALURU");
        jsilvertravellertb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsilvertravellertbActionPerformed(evt);
            }
        });
        getContentPane().add(jsilvertravellertb);
        jsilvertravellertb.setBounds(40, 170, 530, 60);

        jsilvertravellertt.setBackground(new java.awt.Color(153, 153, 153));
        jsilvertravellertt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jsilvertravellertt.setText("TRIVANDRUM-TIRUPATI");
        jsilvertravellertt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsilvertravellerttActionPerformed(evt);
            }
        });
        getContentPane().add(jsilvertravellertt);
        jsilvertravellertt.setBounds(40, 240, 530, 60);

        jsilvertravellertc.setBackground(new java.awt.Color(153, 153, 153));
        jsilvertravellertc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jsilvertravellertc.setText("TRIVANDRUM-CHENNAI");
        jsilvertravellertc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsilvertravellertcActionPerformed(evt);
            }
        });
        getContentPane().add(jsilvertravellertc);
        jsilvertravellertc.setBounds(40, 320, 530, 60);

        jtravellersilver.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhin\\Downloads\\imresizer-1717084224212.jpg")); // NOI18N
        jtravellersilver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtravellersilverActionPerformed(evt);
            }
        });
        getContentPane().add(jtravellersilver);
        jtravellersilver.setBounds(530, 20, 50, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhin\\Downloads\\imresizer-1716963249913.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 610, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jsilvertravellerttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsilvertravellerttActionPerformed
        // TODO add your handling code here:
        new TravellersilverTtot().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jsilvertravellerttActionPerformed

    private void jsilvertravellertbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsilvertravellertbActionPerformed
        // TODO add your handling code here:
        new travellersilverTtoB().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jsilvertravellertbActionPerformed

    private void jsilvertravellertcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsilvertravellertcActionPerformed
        // TODO add your handling code here:
        new travellersilverTtoC().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jsilvertravellertcActionPerformed

    private void jtravellersilverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtravellersilverActionPerformed
        // TODO add your handling code here:
        new packagestraveller().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jtravellersilverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(destinationtraveller2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(destinationtraveller2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(destinationtraveller2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(destinationtraveller2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new destinationtraveller2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jsilvertravellertb;
    private javax.swing.JButton jsilvertravellertc;
    private javax.swing.JButton jsilvertravellertt;
    private javax.swing.JButton jtravellersilver;
    // End of variables declaration//GEN-END:variables
}
