/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author abhin
 */
public class destinationtraveller3 extends javax.swing.JFrame {

    /**
     * Creates new form destinationtraveller3
     */
    public destinationtraveller3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jecotravellertb = new javax.swing.JButton();
        jecotravellertt = new javax.swing.JButton();
        jecotravellertc = new javax.swing.JButton();
        jtravellereco = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 420));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHOOSE DESTINATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 80, 300, 32);

        jecotravellertb.setBackground(new java.awt.Color(153, 153, 153));
        jecotravellertb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jecotravellertb.setText("TRIVANDRUM-BENGALURU");
        jecotravellertb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jecotravellertbActionPerformed(evt);
            }
        });
        getContentPane().add(jecotravellertb);
        jecotravellertb.setBounds(70, 150, 490, 60);

        jecotravellertt.setBackground(new java.awt.Color(153, 153, 153));
        jecotravellertt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jecotravellertt.setText("TRIVANDRUM-TIRUPATI");
        jecotravellertt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jecotravellerttActionPerformed(evt);
            }
        });
        getContentPane().add(jecotravellertt);
        jecotravellertt.setBounds(70, 240, 490, 60);

        jecotravellertc.setBackground(new java.awt.Color(153, 153, 153));
        jecotravellertc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jecotravellertc.setText("TRIVANDRUM-CHENNAI");
        jecotravellertc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jecotravellertcActionPerformed(evt);
            }
        });
        getContentPane().add(jecotravellertc);
        jecotravellertc.setBounds(70, 320, 490, 60);

        jtravellereco.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhin\\Downloads\\imresizer-1717084224212.jpg")); // NOI18N
        jtravellereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtravellerecoActionPerformed(evt);
            }
        });
        getContentPane().add(jtravellereco);
        jtravellereco.setBounds(510, 20, 50, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhin\\Downloads\\imresizer-1716963249913.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 600, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jecotravellertcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jecotravellertcActionPerformed
        // TODO add your handling code here:
        new travellerecoTtoC().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jecotravellertcActionPerformed

    private void jecotravellertbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jecotravellertbActionPerformed
        // TODO add your handling code here:
        new travellerecoTtoB().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jecotravellertbActionPerformed

    private void jecotravellerttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jecotravellerttActionPerformed
        // TODO add your handling code here:
        new TravellerecoTtot().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jecotravellerttActionPerformed

    private void jtravellerecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtravellerecoActionPerformed
        // TODO add your handling code here:
        new packagestraveller().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jtravellerecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(destinationtraveller3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(destinationtraveller3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(destinationtraveller3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(destinationtraveller3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new destinationtraveller3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jecotravellertb;
    private javax.swing.JButton jecotravellertc;
    private javax.swing.JButton jecotravellertt;
    private javax.swing.JButton jtravellereco;
    // End of variables declaration//GEN-END:variables
}
