/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author abhin
 */
public class destination1 extends javax.swing.JFrame {

    /**
     * Creates new form destination1
     */
    public destination1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcarsilvertb = new javax.swing.JButton();
        jcarsilvertt = new javax.swing.JButton();
        jcarsilvertc = new javax.swing.JButton();
        jgoldcar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 420));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHOOSE DESTINATION");
        jLabel1.setRequestFocusEnabled(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 60, 440, 70);

        jcarsilvertb.setBackground(new java.awt.Color(204, 204, 204));
        jcarsilvertb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jcarsilvertb.setText("TRIVANDRUM-BENGALURU");
        jcarsilvertb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcarsilvertbActionPerformed(evt);
            }
        });
        getContentPane().add(jcarsilvertb);
        jcarsilvertb.setBounds(60, 170, 480, 60);

        jcarsilvertt.setBackground(new java.awt.Color(204, 204, 204));
        jcarsilvertt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jcarsilvertt.setText("TRIVANDRUM-TIRUPATI");
        jcarsilvertt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcarsilverttActionPerformed(evt);
            }
        });
        getContentPane().add(jcarsilvertt);
        jcarsilvertt.setBounds(60, 250, 480, 60);

        jcarsilvertc.setBackground(new java.awt.Color(204, 204, 204));
        jcarsilvertc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jcarsilvertc.setText("TRIVANDRUM-CHENNAI");
        jcarsilvertc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcarsilvertcActionPerformed(evt);
            }
        });
        getContentPane().add(jcarsilvertc);
        jcarsilvertc.setBounds(60, 330, 480, 50);

        jgoldcar.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhin\\Downloads\\imresizer-1717084224212.jpg")); // NOI18N
        jgoldcar.setText("jButton1");
        jgoldcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jgoldcarActionPerformed(evt);
            }
        });
        getContentPane().add(jgoldcar);
        jgoldcar.setBounds(510, 20, 50, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhin\\Downloads\\imresizer-1716963249913.png")); // NOI18N
        jLabel2.setMinimumSize(new java.awt.Dimension(620, 420));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 600, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcarsilvertbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcarsilvertbActionPerformed
        // TODO add your handling code here:
        new CarsilverTtoB().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jcarsilvertbActionPerformed

    private void jcarsilverttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcarsilverttActionPerformed
        // TODO add your handling code here:
        new carsilverTtoT().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jcarsilverttActionPerformed

    private void jcarsilvertcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcarsilvertcActionPerformed
        // TODO add your handling code here:
        new carsilverTtoC().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jcarsilvertcActionPerformed

    private void jgoldcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jgoldcarActionPerformed
        // TODO add your handling code here:
        new types().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jgoldcarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(destination1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(destination1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(destination1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(destination1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new destination1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jcarsilvertb;
    private javax.swing.JButton jcarsilvertc;
    private javax.swing.JButton jcarsilvertt;
    private javax.swing.JButton jgoldcar;
    // End of variables declaration//GEN-END:variables
}
