/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author abhin
 */
public class destination extends javax.swing.JFrame {

    /**
     * Creates new form destination
     */
    public destination() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcargoldtb = new javax.swing.JButton();
        jcargoldtt = new javax.swing.JButton();
        jcargoldtc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jcargpre = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 420));
        getContentPane().setLayout(null);

        jcargoldtb.setBackground(new java.awt.Color(204, 204, 204));
        jcargoldtb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jcargoldtb.setText("    TRIVANDRUM-BENGALURU");
        jcargoldtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcargoldtbActionPerformed(evt);
            }
        });
        getContentPane().add(jcargoldtb);
        jcargoldtb.setBounds(40, 150, 540, 60);

        jcargoldtt.setBackground(new java.awt.Color(204, 204, 204));
        jcargoldtt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jcargoldtt.setText("TRIVANDRUM-TIRUPATI");
        jcargoldtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcargoldttActionPerformed(evt);
            }
        });
        getContentPane().add(jcargoldtt);
        jcargoldtt.setBounds(40, 230, 540, 60);

        jcargoldtc.setBackground(new java.awt.Color(204, 204, 204));
        jcargoldtc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jcargoldtc.setText("TRIVANDRUM-CHENNAI");
        jcargoldtc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcargoldtcActionPerformed(evt);
            }
        });
        getContentPane().add(jcargoldtc);
        jcargoldtc.setBounds(40, 310, 540, 60);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHOOSE DESTINATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 70, 413, 40);

        jcargpre.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhin\\Downloads\\imresizer-1717084224212.jpg")); // NOI18N
        jcargpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcargpreActionPerformed(evt);
            }
        });
        getContentPane().add(jcargpre);
        jcargpre.setBounds(530, 10, 50, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhin\\Downloads\\imresizer-1716963249913.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 600, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcargoldttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcargoldttActionPerformed
        // TODO add your handling code here:
        new CarGoldTtoT().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jcargoldttActionPerformed

    private void jcargoldtcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcargoldtcActionPerformed
        // TODO add your handling code here:
        new cargoldTtoC().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jcargoldtcActionPerformed

    private void jcargoldtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcargoldtbActionPerformed
        // TODO add your handling code here:
        new CarGoldTVMBLR().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jcargoldtbActionPerformed

    private void jcargpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcargpreActionPerformed
        // TODO add your handling code here:
        new types().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jcargpreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(destination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(destination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(destination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(destination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new destination().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jcargoldtb;
    private javax.swing.JButton jcargoldtc;
    private javax.swing.JButton jcargoldtt;
    private javax.swing.JButton jcargpre;
    // End of variables declaration//GEN-END:variables
}
