/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author abhin
 */
public class destination2 extends javax.swing.JFrame {

    /**
     * Creates new form destination2
     */
    public destination2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcarecotb = new javax.swing.JButton();
        jcarecott = new javax.swing.JButton();
        jcarecotc = new javax.swing.JButton();
        jcar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 420));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHOOSE DESTINATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 70, 473, 48);

        jcarecotb.setBackground(new java.awt.Color(204, 204, 204));
        jcarecotb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jcarecotb.setText("TRIVANDRUM-BENGALURU");
        jcarecotb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcarecotbActionPerformed(evt);
            }
        });
        getContentPane().add(jcarecotb);
        jcarecotb.setBounds(60, 160, 490, 60);

        jcarecott.setBackground(new java.awt.Color(204, 204, 204));
        jcarecott.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jcarecott.setText("TRIVANDRUM-TIRUPATI");
        jcarecott.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcarecottActionPerformed(evt);
            }
        });
        getContentPane().add(jcarecott);
        jcarecott.setBounds(60, 240, 490, 60);

        jcarecotc.setBackground(new java.awt.Color(204, 204, 204));
        jcarecotc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jcarecotc.setText("TRIVADRUM-CHENNAI");
        jcarecotc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcarecotcActionPerformed(evt);
            }
        });
        getContentPane().add(jcarecotc);
        jcarecotc.setBounds(60, 320, 490, 60);

        jcar.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhin\\Downloads\\imresizer-1717084224212.jpg")); // NOI18N
        jcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcarActionPerformed(evt);
            }
        });
        getContentPane().add(jcar);
        jcar.setBounds(510, 20, 50, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhin\\Downloads\\imresizer-1716963249913.png")); // NOI18N
        jLabel2.setMinimumSize(new java.awt.Dimension(620, 420));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 600, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcarecotbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcarecotbActionPerformed
        // TODO add your handling code here:
        new CarECTtoB().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jcarecotbActionPerformed

    private void jcarecottActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcarecottActionPerformed
        // TODO add your handling code here:
        new CARECOTtoT().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jcarecottActionPerformed

    private void jcarecotcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcarecotcActionPerformed
        // TODO add your handling code here:
        new carEcoTtoC().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jcarecotcActionPerformed

    private void jcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcarActionPerformed
        // TODO add your handling code here:
        new types().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jcarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(destination2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(destination2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(destination2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(destination2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new destination2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jcar;
    private javax.swing.JButton jcarecotb;
    private javax.swing.JButton jcarecotc;
    private javax.swing.JButton jcarecott;
    // End of variables declaration//GEN-END:variables
}
