/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
/**
 *
 * @author abhin
 */
public class moredetailsc1 extends javax.swing.JFrame {

    /**
     * Creates new form moredetailsc1
     */
    public moredetailsc1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Ds = new javax.swing.JLabel();
        Oc = new javax.swing.JLabel();
        Tc = new javax.swing.JLabel();
        Pro = new javax.swing.JLabel();
        M = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        String query = ("select *  from cars where RegistrationNumber='KL-23-AB-1234'");
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fleat_management", "root", "abhinav2004@");
             PreparedStatement pstmt = con.prepareStatement(query))
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            ResultSet rs=pstmt.executeQuery();
            while (rs.next()){
                String Ma=rs.getString(7);
                String D=rs.getString(9);
                String O=rs.getString(10);
                String T=rs.getString(11);
                String P=rs.getString(12);
                M.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                M.setText(Ma);
                Ds.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                Ds.setText(D);
                Oc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                Oc.setText(O);
                Tc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                Tc.setText(T);
                Pro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                Pro.setText(P);


            }
        } catch (Exception e) {
            e.printStackTrace();
}

        setMinimumSize(new java.awt.Dimension(620, 420));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("SPLIT FARE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(96, 0, 189, 48);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("MAINTENACE FARE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(6, 81, 167, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("DRIVER'S SALARY");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(6, 125, 167, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("OPERATIONAL CHARGE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(6, 170, 221, 25);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(157, 214, 37, 25);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("TOTAL CHARGES");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(6, 214, 145, 25);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("PROFIT");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(6, 245, 73, 25);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(428, 75, 27, 0);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(428, 75, 27, 0);
        getContentPane().add(Ds);
        Ds.setBounds(215, 125, 240, 27);
        getContentPane().add(Oc);
        Oc.setBounds(233, 170, 222, 26);
        getContentPane().add(Tc);
        Tc.setBounds(200, 214, 249, 25);
        getContentPane().add(Pro);
        Pro.setBounds(200, 245, 140, 28);
        getContentPane().add(M);
        M.setBounds(215, 81, 208, 25);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhin\\Downloads\\imresizer-1717441186590.png")); // NOI18N
        jLabel10.setMinimumSize(new java.awt.Dimension(600, 400));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, -30, 600, 480);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(moredetailsc1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(moredetailsc1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(moredetailsc1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(moredetailsc1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new moredetailsc1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel Ds;
    private javax.swing.JLabel M;
    private javax.swing.JLabel Oc;
    private javax.swing.JLabel Pro;
    private javax.swing.JLabel Tc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration
}
