/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author abhin
 */
public class packagesbus extends javax.swing.JFrame {

    /**
     * Creates new form packagesbus
     */
    public packagesbus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jgoldbus = new javax.swing.JButton();
        jsilverbus = new javax.swing.JButton();
        jecobus = new javax.swing.JButton();
        jprevfleat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 420));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 102, 0));
        jLabel1.setText("CATEGORY");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 0, 190, 48);

        jgoldbus.setBackground(new java.awt.Color(153, 102, 0));
        jgoldbus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jgoldbus.setForeground(new java.awt.Color(255, 255, 255));
        jgoldbus.setText("GOLD ");
        jgoldbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jgoldbusActionPerformed(evt);
            }
        });
        getContentPane().add(jgoldbus);
        jgoldbus.setBounds(210, 150, 160, 30);

        jsilverbus.setBackground(new java.awt.Color(204, 204, 204));
        jsilverbus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jsilverbus.setText("SILVER");
        jsilverbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsilverbusActionPerformed(evt);
            }
        });
        getContentPane().add(jsilverbus);
        jsilverbus.setBounds(210, 220, 160, 30);

        jecobus.setBackground(new java.awt.Color(0, 0, 0));
        jecobus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jecobus.setForeground(new java.awt.Color(204, 204, 204));
        jecobus.setText("ECONOMY");
        jecobus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jecobusActionPerformed(evt);
            }
        });
        getContentPane().add(jecobus);
        jecobus.setBounds(210, 290, 160, 30);

        jprevfleat.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhin\\Downloads\\imresizer-1717084224212.jpg")); // NOI18N
        jprevfleat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jprevfleatActionPerformed(evt);
            }
        });
        getContentPane().add(jprevfleat);
        jprevfleat.setBounds(10, 10, 50, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhin\\Downloads\\imresizer-1717052201292.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 600, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jgoldbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jgoldbusActionPerformed
        // TODO add your handling code here:
        new destinationbus1().setVisible(true);
        this.setVisible(false);
       
    }//GEN-LAST:event_jgoldbusActionPerformed

    private void jsilverbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsilverbusActionPerformed
        // TODO add your handling code here:
        new destinationbus2().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jsilverbusActionPerformed

    private void jecobusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jecobusActionPerformed
        // TODO add your handling code here:
        new destinationbus3().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jecobusActionPerformed

    private void jprevfleatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jprevfleatActionPerformed
        // TODO add your handling code here:
        new fleatoptions().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jprevfleatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(packagesbus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(packagesbus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(packagesbus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(packagesbus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new packagesbus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jecobus;
    private javax.swing.JButton jgoldbus;
    private javax.swing.JButton jprevfleat;
    private javax.swing.JButton jsilverbus;
    // End of variables declaration//GEN-END:variables
}
