/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author abhin
 */
public class packagestraveller extends javax.swing.JFrame {

    /**
     * Creates new form packagestraveller
     */
    public packagestraveller() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jgoldtraveller = new javax.swing.JButton();
        jsilvertraveller = new javax.swing.JButton();
        jecotraveller = new javax.swing.JButton();
        jprevtraveller = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 420));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 102, 0));
        jLabel1.setText("CATEGORY");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 0, 200, 48);

        jgoldtraveller.setBackground(new java.awt.Color(153, 102, 0));
        jgoldtraveller.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jgoldtraveller.setForeground(new java.awt.Color(255, 255, 255));
        jgoldtraveller.setText("GOLD");
        jgoldtraveller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jgoldtravellerActionPerformed(evt);
            }
        });
        getContentPane().add(jgoldtraveller);
        jgoldtraveller.setBounds(210, 150, 160, 30);

        jsilvertraveller.setBackground(new java.awt.Color(204, 204, 204));
        jsilvertraveller.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jsilvertraveller.setText("SILVER");
        jsilvertraveller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsilvertravellerActionPerformed(evt);
            }
        });
        getContentPane().add(jsilvertraveller);
        jsilvertraveller.setBounds(210, 220, 160, 30);

        jecotraveller.setBackground(new java.awt.Color(0, 0, 0));
        jecotraveller.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jecotraveller.setForeground(new java.awt.Color(204, 204, 204));
        jecotraveller.setText("ECONOMY");
        jecotraveller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jecotravellerActionPerformed(evt);
            }
        });
        getContentPane().add(jecotraveller);
        jecotraveller.setBounds(210, 290, 160, 30);

        jprevtraveller.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhin\\Downloads\\imresizer-1717084224212.jpg")); // NOI18N
        jprevtraveller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jprevtravellerActionPerformed(evt);
            }
        });
        getContentPane().add(jprevtraveller);
        jprevtraveller.setBounds(10, 10, 50, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhin\\Downloads\\imresizer-1717052201292.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 600, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jgoldtravellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jgoldtravellerActionPerformed
        // TODO add your handling code here:
        new destintiontraveller1().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jgoldtravellerActionPerformed

    private void jsilvertravellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsilvertravellerActionPerformed
        // TODO add your handling code here:
        new destinationtraveller2().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jsilvertravellerActionPerformed

    private void jecotravellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jecotravellerActionPerformed
        // TODO add your handling code here:
        new destinationtraveller3().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jecotravellerActionPerformed

    private void jprevtravellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jprevtravellerActionPerformed
        // TODO add your handling code here:
        new fleatoptions().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jprevtravellerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(packagestraveller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(packagestraveller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(packagestraveller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(packagestraveller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new packagestraveller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jecotraveller;
    private javax.swing.JButton jgoldtraveller;
    private javax.swing.JButton jprevtraveller;
    private javax.swing.JButton jsilvertraveller;
    // End of variables declaration//GEN-END:variables
}
