/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author abhin
 */
public class types extends javax.swing.JFrame {

    /**
     * Creates new form types
     */
    public types() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jgold = new javax.swing.JButton();
        jsilver = new javax.swing.JButton();
        jeconomic = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 420));
        getContentPane().setLayout(null);

        jgold.setBackground(new java.awt.Color(153, 102, 0));
        jgold.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jgold.setForeground(new java.awt.Color(255, 255, 255));
        jgold.setText("GOLD");
        jgold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jgoldActionPerformed(evt);
            }
        });
        getContentPane().add(jgold);
        jgold.setBounds(210, 170, 160, 30);

        jsilver.setBackground(new java.awt.Color(204, 204, 204));
        jsilver.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jsilver.setText("SILVER");
        jsilver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsilverActionPerformed(evt);
            }
        });
        getContentPane().add(jsilver);
        jsilver.setBounds(210, 230, 160, 30);

        jeconomic.setBackground(new java.awt.Color(0, 0, 0));
        jeconomic.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jeconomic.setForeground(new java.awt.Color(204, 204, 204));
        jeconomic.setText("ECONOMY");
        jeconomic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeconomicActionPerformed(evt);
            }
        });
        getContentPane().add(jeconomic);
        jeconomic.setBounds(210, 290, 160, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 0));
        jLabel1.setText("CATEGORY");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 10, 190, 30);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhin\\Downloads\\imresizer-1717084224212.jpg")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 10, 50, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhin\\Downloads\\imresizer-1717052201292.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 600, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jgoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jgoldActionPerformed
        // TODO add your handling code here:
        new destination().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jgoldActionPerformed

    private void jsilverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsilverActionPerformed
        // TODO add your handling code here:
        new destination1().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jsilverActionPerformed

    private void jeconomicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeconomicActionPerformed
        // TODO add your handling code here:
        new destination2().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jeconomicActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new fleatoptions().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(types.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(types.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(types.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(types.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new types().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jeconomic;
    private javax.swing.JButton jgold;
    private javax.swing.JButton jsilver;
    // End of variables declaration//GEN-END:variables
}
